services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password
      KC_DB: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_HOST: db
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT_HTTPS: "false"
      JAVA_OPTS_APPEND: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    command: ["start-dev"]
    volumes:
      - ./target/deploy:/opt/keycloak/providers/
      - ./src/main/resources/theme:/opt/keycloak/themes/
    ports:
    - "8080:8080"
    - "5005:5005"
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password